# Generated by Django 5.1.6 on 2025-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_droneuser_citizenship_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droneuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='droneuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='droneuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
    ]
