# Generated by Django 5.1.6 on 2025-02-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_droneuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
